from typing_extensions import deprecated

LITERALS: list[str]

SYMBOLS: dict[str, str]

__all__: list[str]

@deprecated("introduced _is_char for character validation")
def _is_chars(*chars: tuple[str]) -> bool: ...
def _is_char(char: str) -> bool: ...
def strip_punctuation(value: str, *args: tuple[str]) -> str: ...
def parse_url(url: str) -> str: ...
